package render

import (
	"fmt"
	"strings"

	"github.com/rendaman0215/flakehound/internal/diagnosis"
)

const Marker = "<!-- flakehound-diagnosis -->"

func Markdown(d *diagnosis.Diagnosis) string {
	var b strings.Builder
	b.WriteString(Marker + "\n")
	b.WriteString("## 🐶 Flakehound Diagnosis\n\n")
	fmt.Fprintf(&b, "**Failure type:** %s  \n", display(d.FailureType, "unknown"))
	fmt.Fprintf(&b, "**Retryable:** %s  \n", title(display(d.Retryable, "unknown")))
	fmt.Fprintf(&b, "**Confidence:** %.2f  \n", d.Confidence)
	fmt.Fprintf(&b, "**Owner hint:** %s\n\n", display(d.OwnerHint, "unknown"))
	b.WriteString("### What happened\n\n")
	b.WriteString(display(d.Summary, "No summary was returned.") + "\n\n")
	b.WriteString("### Likely cause\n\n")
	b.WriteString(display(d.LikelyCause, "Unknown from the available evidence.") + "\n\n")
	b.WriteString("### What you should do next\n\n")
	writeNumbered(&b, d.NextActions, "Review the evidence below and inspect the failed job logs.")
	b.WriteString("\n### Evidence\n\n")
	writeBullets(&b, d.Evidence, "No specific evidence was returned.")
	b.WriteString("\n---\n\n_Comment generated by Flakehound._\n")
	return b.String()
}

func writeNumbered(b *strings.Builder, values []string, fallback string) {
	if len(values) == 0 {
		values = []string{fallback}
	}
	for i, value := range values {
		fmt.Fprintf(b, "%d. %s\n", i+1, value)
	}
}

func writeBullets(b *strings.Builder, values []string, fallback string) {
	if len(values) == 0 {
		values = []string{fallback}
	}
	for _, value := range values {
		value = strings.Join(strings.Fields(value), " ")
		value = strings.TrimLeft(value, "- *")
		fmt.Fprintf(b, "- `%s`\n", strings.ReplaceAll(value, "`", "'"))
	}
}

func display(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}

func title(value string) string {
	if value == "" {
		return value
	}
	return strings.ToUpper(value[:1]) + value[1:]
}
